apiVersion: v1
kind: Pod
metadata:
  name: back-test-pod
  labels:
    name: back-test-pod
spec:
  containers:
  - name: back-test-pod
    image: ander11110/backend-coding-test:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
