name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  prepare_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install dependencies
      run: npm i
    - name: Linting your code
      run: npm run lint
    - name: Building your code
      run: npm run build
    - name: Upload builded app to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: builded_app
        path: dist
    - name: Testing your code
      run: npm run test

  deploy:
    needs: prepare_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download builded_app from artifacts
        uses: actions/download-artifact@v2
        with:
          name: builded_app
      - shell: bash
        # run: "[ -d \"dist\" ] && echo \"Artifacts exists.\" || echo \"Error: Artifacts does not exists.\""
        run: ls
      - name: Mark current main as new version of app
        run: echo Set new tag in main branch
      - name: Download builded_app to server and run
        run: echo Preparing a Heroku server...
